In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split

In [30]:
dataset = pd.read_csv('StudentsPerformance.csv')

In [31]:
dataset['average_score']=((dataset["math_score"]+dataset["reading_score"]+dataset["writing_score"])/3).round()
dataset['results'] = np.where(dataset['average_score']>= 50, '1', '0')
dataset.head()

Unnamed: 0  gender race_ethnicity parental_level_of_education  \
0           1  female        group B           bachelor's degree   
1           2  female        group C                some college   
2           3  female        group B             master's degree   
3           4    male        group A          associate's degree   
4           5    male        group C                some college   

          lunch test_preparation_course  math_score  reading_score  \
0      standard                    none          72             72   
1      standard               completed          69             90   
2      standard                    none          90             95   
3  free/reduced                    none          47             57   
4      standard                    none          76             78   

   writing_score  average_score results  
0             74           73.0       1  
1             88           82.0       1  
2             93           93.0       1  
3             44           49.0       0  
4             75           76.0       1

In [32]:
from sklearn.preprocessing import LabelEncoder
label_encoder= LabelEncoder()
dataset['gender'] = label_encoder.fit_transform(dataset['gender'])
dataset['race_ethnicity'] = label_encoder.fit_transform(dataset['race_ethnicity'])
dataset['parental_level_of_education'] = label_encoder.fit_transform(dataset['parental_level_of_education'])
dataset['lunch'] = label_encoder.fit_transform(dataset['lunch'])
dataset['test_preparation_course'] = label_encoder.fit_transform(dataset['test_preparation_course'])
dataset.head()

Unnamed: 0  gender  race_ethnicity  parental_level_of_education  lunch  \
0           1       0               1                            1      1   
1           2       0               2                            4      1   
2           3       0               1                            3      1   
3           4       1               0                            0      0   
4           5       1               2                            4      1   

   test_preparation_course  math_score  reading_score  writing_score  \
0                        1          72             72             74   
1                        0          69             90             88   
2                        1          90             95             93   
3                        1          47             57             44   
4                        1          76             78             75   

   average_score results  
0           73.0       1  
1           82.0       1  
2           93.0       1  
3           49.0       0  
4           76.0       1

In [33]:
x=dataset.iloc[:,[1,3]]  #Independent variable
y=dataset.iloc[:,-1]   #Target variable
f_score=chi2(x,y)   #returns f score and p value 
f_score

(array([4.39004149, 2.24260302]), array([0.03614943, 0.1342548 ]))

In [34]:
x=dataset.iloc[:,:6]  
y=dataset.iloc[:,-1]   
f_score=chi2(x,y)  
f_score

(array([845.67841048,   4.39004149,   7.53633855,   2.24260302,
         10.34022394,   5.48355832]),
 array([6.32545595e-186, 3.61494334e-002, 6.04667974e-003, 1.34254805e-001,
        1.30162219e-003, 1.91961441e-002]))

In [35]:
p_value=pd.Series(f_score[1],index=x.columns)
p_value.sort_values(ascending=True,inplace=True)

In [36]:
print(p_value)

Unnamed: 0                     6.325456e-186
lunch                           1.301622e-03
race_ethnicity                  6.046680e-03
test_preparation_course         1.919614e-02
gender                          3.614943e-02
parental_level_of_education     1.342548e-01
dtype: float64


In [37]:
x=dataset.iloc[:,[1,3,5]]  
y=dataset.iloc[:,-1]   
f_score=chi2(x,y)  
f_score

(array([4.39004149, 2.24260302, 5.48355832]),
 array([0.03614943, 0.1342548 , 0.01919614]))

In [38]:
p_value=pd.Series(f_score[1],index=x.columns)
p_value.sort_values(ascending=True,inplace=True)

In [39]:
print(p_value)

test_preparation_course        0.019196
gender                         0.036149
parental_level_of_education    0.134255
dtype: float64
